---

- name: Wait for Jenkins to start up
  uri:
    url: "http://{{ jenkins_server.hostname_local }}:{{ jenkins_server.http_port }}/jnlpJars/jenkins-cli.jar"
    method: GET
    status_code: 200,403
  register: jenkins_service_check
  until: (
      jenkins_service_check.status == 200
      or jenkins_service_check.status == 403
    )
    and jenkins_service_check.msg.find("Please wait while") == -1
  retries: "{{ jenkins_server.start_up_retry }}"
  delay: "{{ jenkins_server.start_up_delay }}"
